POST http://localhost:3000/photos HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJLQW1pbCIsImVtYWlsIjoia2FtaWxAd3AucGwiLCJpYXQiOjE3ODE4NjIzNjIsImV4cCI6MTc4MTk0ODc2Mn0.n7sYf5dbIw7FxKQu3-bRzPqgLqK1-Sa36BGPA3U7uoo
Content-Type: multipart/form-data; boundary=WebKitFormBoundaryX

--WebKitFormBoundaryX
Content-Disposition: form-data; name="body"
Content-Type: application/json

{
    "description":"asd",
    "tags": [
        "hero",
        "uno2"
    ]
}

--WebKitFormBoundaryX
Content-Disposition: form-data; name="photo_data"; filename="test.jpg"
Content-Type: image/jpeg

< ./test.jpg
--WebKitFormBoundaryX--